name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  build_and_deploy:
    container: gabrieleara/dev_environment:latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Generating CVs
        run: ./generate-cvs.sh
      - name: 'DEBUG: printing something I should not print'
        run: echo ${{ secrets.API_TOKEN_GITHUB }}
      - name: Deploy on Personal Website
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'cvs'
          destination-github-username: 'gabrieleara'
          destination-repository-name: 'gabrieleara.github.io'
          target-directory: 'docs/assets/documents/cv'
          user-email: 'gabriele.ara@live.it'
          user-name: 'Gabriele Ara'
          github-server: 'github.com'
          destination-repository-username: 'gabrieleara'
          commit-message: "Updating CVs: ${{ github.event.head_commit.message }}"
          target-branch: 'main'
