name: Build and Deploy on Personal Website
on:
  push:
    branches:
      - master
      - main
jobs:
  build_and_deploy:
    container: gabrieleara/dev_environment:latex
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Generate CVs
        run: ./generate-cvs.sh
        env:
          CV_ONLINE_ONLY: '1'
      - name: Deploy on Personal Website
        uses: gabrieleara/github-action-push-to-another-repository@issue-cpina-68
        env:
          API_TOKEN_GITHUB: '${{ secrets.API_TOKEN_GITHUB }}'
        with:
          source-directory: 'cvs'
          destination-github-username: 'gabrieleara'
          destination-repository-name: 'gabrieleara.github.io'
          target-directory: 'docs/assets/documents/cv'
          user-email: 'gabriele.ara@live.it'
          user-name: 'Gabriele Ara'
          github-server: 'github.com'
          destination-repository-username: 'gabrieleara'
          commit-message: "Updating CVs: ${{ github.event.head_commit.message }}"
          target-branch: 'main'
